version: "3"
services:
  frontend:
    build: ./client
    ports:
      - "5173:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres/testDevOps
    ports:
      - "5001:5000"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: testDevOps
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:

